baseurl = "https://blog.bkristian.net/"
title = "Home"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

# [services]
# [services.disqus]
# shortname = "bkstrand"

[markup.highlight]
style = "github-dark"

[params]
  author = "Bjørn Kristian Strand"
  info = "Kuberntes Engineer @ Telenor"
  description = "Personal Blog"
  keywords = "blog,developer,personal"
  avatarurl = "images/fugl.jpeg"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2026

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/bksuup"
[[params.social]]
  name = "Gitlab"
  icon = "fa-brands fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/bksuup"
# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 2
  url = "projects/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
